before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_image:
  script:
    - docker build -t $CI_REGISTRY/skyvalley/auth:$CI_COMMIT_SHA $CI_REGISTRY/skyvalley/auth:latest .
    - docker push $CI_REGISTRY/skyvalley/auth