stages:
  - build
  - test
  - release

services:
  - docker:19.03.12-dind

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE: $CI_REGISTRY/skyvalley/auth:$CI_COMMIT_SHORT_SHA
  IMAGE_LATEST: $CI_REGISTRY/skyvalley/auth:latest

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin

build:
  stage: build
  script:
    - docker build -t $IMAGE -t $IMAGE_LATEST .
    - docker push $IMAGE
    - docker push $IMAGE_LATEST

test:
  stage: test
  services:
    - redis:latest
  script:
    - docker pull $IMAGE
    - docker run -e REDIS_HOST=redis -e REDIS_PORT=6379 $IMAGE

release:
  stage: release
  script:
    - echo "This is where the image switching should happen"
  only:
    - master
