stages:
  - build
  - test
  - release

variables:
  IMAGE: $CI_REGISTRY/skyvalley/auth:CI_COMMIT_SHORT_SHA

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE

test:
  stage: test
  script:
    - echo "This is where the tests should run"

release:
  stage: release
  script:
    - echo "This is where the image switching should happen"
  only:
    - master
