stages:
  - build
  - test
  - staging
  - release

services:
  - docker:19.03.12-dind

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE: $CI_REGISTRY/skyvalley/auth:$CI_COMMIT_SHORT_SHA
  IMAGE_LATEST: $CI_REGISTRY/skyvalley/auth:latest

build:
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t $IMAGE -t $IMAGE_LATEST .
    - docker push $IMAGE
    - docker push $IMAGE_LATEST

test:
  stage: test
  image: node
  services:
    - redis:latest
    - mongo:latest
  variables:
    REDIS_HOST: redis
    REDIS_PORT: 6379
    MONGODB_HOST: mongo
    MONGODB_PORT: 27017
  script:
    - npm install
    - npm test

staging:
  stage: staging
  trigger:
    project: skyvalley/integration_tests
    branch: master


release:
  stage: release
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - echo "This is where the image switching should happen"
  only:
    - master
  when: manual